title: Stefan Gotteswinter - Technical Bulletin
description: The marvelous world of machining and engineering
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
show_downloads: false
